In [1]:
import numpy as np

In [6]:
u = np.array([2,4,5,6])
v = np.array([1,0,0,2])

In [8]:
u

array([2, 4, 5, 6])

In [9]:
v

array([1, 0, 0, 2])

Vector-Vector Multiplication

In [20]:
def vector_vector_multiplication(u,v):
    assert u.shape[0]  == v.shape[0]  #ensures shape of both vectors are equal
    n = u.shape[0]
    results = 0.0

    for i in range(n):
        results = results + u[i] * v[i]

    return results

#this is mathematical representation of formula in code
vector_vector_multiplication(u,v)

14.0

In [21]:
#numpy formula for v-v multiplaction
u.dot(v)

14

Matrix-Vector Multiplication

In [22]:
U = np.array([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,2,1]
])

In [28]:
def matrix_vector_multiplication(U,v):
    assert U.shape[1] == v.shape[0]
    num_rows = U.shape[0]
    results = np.zeros(num_rows)

    for i in range(num_rows):
        results[i] = vector_vector_multiplication(U[i], v)
    return results
    
matrix_vector_multiplication(U,v)

#python code for mathematical formula

array([14.,  5.,  5.])

In [29]:
#numy code for maths formula
U.dot(v)

array([14,  5,  5])

Matrix-Matrix Multiplication

In [32]:
V = np.array([
    [1 , 1, 2],
    [0, 0.5, 1],
    [0 ,2 , 1],
    [2, 1 ,0]
])

In [33]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [34]:
def matrix_matrix_multiplication(U,V):
    assert U.shape[0] == V.shape[1]
    num_rows = U.shape[0]
    num_columns =V.shape[1]
    results = np.zeros((num_rows, num_columns))

    for i in range(num_columns):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        results[:, i] = Uvi
    return results
    
matrix_matrix_multiplication(U,V)

#python code for mathematical formula

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])