Numpy Tutorials

In [5]:
import numpy as np

Creating arrays

In [7]:
np.zeros(5) #creates an array of 5 zeros. #np.ones(10) creates an array of 10 one.

array([0., 0., 0., 0., 0.])

In [8]:
np.full(10, 2.5) #creates an array first arg is number of times, sec arg is value

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [10]:
a = np.array([1, 4, 6, 7,8 ]) #creates array of choice

In [11]:
a

array([1, 4, 6, 7, 8])

In [12]:
np.linspace(2, 20, 10) #creates an array between 2 and 20 with 10 values

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

Multi-Dimensional Arrays

In [13]:
np.zeros((5, 2)) #creates an array of 0 with 5 rows and 2 columns

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
n = np.array([[1,2,3],
          [4,5,6],
          [7,8,9]
         ])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
#n[1,2] #points to 2nd row and 3rd column ,starts counting from 0
n[2,2] = 1 # changes value of 3rd row, 3rd cloumn to 1
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 1]])

In [ ]:
#n[1]  gives only 2nd row
n[1] = [3, 5, 6] assigns 